### PR TITLE
Make account meta private

### LINKED ISSUE #1391: Incoming output isn't synced on account after first login
## Bug description

In Firefly:

i am logged into an account and request some fund from the faucet to simulate a soon incoming output for my account. Then i log out and stay logged out until i'm sure the funds arrived (i checked the explorer). When i log back in, the account doesn't contain this output, only if i logout and again login, it appears

## Rust version

Which version of Rust are you running?

- Rust version: 2.0.2-alpha.21

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. get output while offline
2. log into account
3. output isnt synced yet
4. logout
5. login
6. output is now there

## Expected behaviour

Output should be available after first login

## Actual behaviour

Output is available after second login

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Make account meta private, because the data there isn't updated, one should call the account methods instead to get up to date data

## Links to any relevant issues

Fixes https://github.com/iotaledger/wallet.rs/issues/1391

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by MarkNerdi996 — CHANGES_REQUESTED** [review]
I just checked all the getter methods, and the methd `listIncomingTransactions()` is missing.  Could you please add that

File: src/account/handle.rs [hunk 1]
```diff
@@ -188,7 +188,15 @@ impl AccountHandle {
         Ok(outputs)
     }
 
-    /// Returns all transaction of the account
+    /// Returns all incoming transactions of the account
+    pub async fn list_incoming_transactions(
+        &self,
+    ) -> Result<Vec<(TransactionId, (TransactionPayload, Vec<OutputResponse>))>> {
```
Comment (thibault-martinez) [inline src/account/handle.rs]: Just curious why a second tuple in the tuple?

Comment (thibault-martinez) [reply src/account/handle.rs]: Make it look like a Hashmap?

**Review by thibault-martinez — DISMISSED** [review]

File: src/account/handle.rs (hunk 1 above)
Comment (Thoralf-M) [reply src/account/handle.rs]: Hm yeah because it's one, probably better to also return it as one, just remembered that there was something with returning it in nodejs as hashmap, but that's also fine
Will change

**Review by thibault-martinez — DISMISSED** [review]

**Review by samuel-rufi — DISMISSED** [review]

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
Conflicts

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
Conflict :trollface:

File: bindings/nodejs/lib/Account.ts [hunk 2]
```diff
@@ -216,6 +220,34 @@ export class Account {
         return JSON.parse(resp).payload;
     }
 
+    /**
+     * Melt native tokens. This happens with the foundry output which minted them, by increasing it's
```
Comment (thibault-martinez) [inline bindings/nodejs/lib/Account.ts]:
```suggestion
     * Melt native tokens. This happens with the foundry output which minted them, by increasing its
```

**Review by thibault-martinez — APPROVED** [review]

**Review by MarkNerdi996 — APPROVED** [review]
Looks good for me! 
If a differentiation between `publicAddresses` and `internalAddresses` is needed, i'll let you know
