### PR TITLE
Fix restore_backup

### LINKED ISSUE #1170: [Bug]: RestoreBackup always fails if wrong password provided once
### Issue description

If the wrong password is supplied once to the `restore_backup()`, the stronghold decryption will fail even if the correct password is supplied afterwards.

### Version

https://github.com/iotaledger/wallet.rs/commit/e4cbe82ceb74b3bbd36226c6620fab8161e88941

### Expected behaviour

Steps:
1) Supply wrong password
2) RestoreBackup fails
3) Supply correct password
4) RestoreBackup succeeds

### Actual behaviour

Steps:
1) Supply wrong password
2) RestoreBackup fails
3) Supply correct password
4) RestoreBackup fails

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Steps:
1) Supply wrong password
2) RestoreBackup fails
3) Supply correct password
4) RestoreBackup fails

### Errors

```
{"type":"Error","payload":{"type":"ClientError","error":"`Stronghold reported a procedure error: Engine Error: Crypto Error: `error in algorithm XCHACHA20-POLY1305`, Unable to read snapshot. Please try another password.`"}}
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Always create a new Stronghold when restoring, so only the password of the snapshot is required

## Links to any relevant issues

Fixes #1170 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

## How the change has been tested

Updated test

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Tuditi — DISMISSED** [review]
Works for me! :partying_face:

File: src/account_manager/operations/backup.rs [hunk 1]
```diff
@@ -68,29 +68,25 @@ impl AccountManager {
 
         let mut secret_manager = self.secret_manager.as_ref().write().await;
         let mut new_secret_manager = None;
+        // Get the current snapshot path if set
+        let mut snapshot_path = None;
```
Comment (thibault-martinez) [inline src/account_manager/operations/backup.rs]: Bit nitpicky but I'd rather have an if/else than a mutable variable

Comment (Thoralf-M) [reply src/account_manager/operations/backup.rs]: Like this? Doesn't look better to me
`````Rust
        if let SecretManager::Stronghold(stronghold) = &mut *secret_manager {
            // We'll create a new stronghold to load the backup
            let mut new_stronghold = StrongholdSecretManager::builder().try_build()?;
            // Get the current snapshot path if set
            new_stronghold.snapshot_path = stronghold.snapshot_path.clone();
            read_data_from_stronghold_backup(
                self,
                &mut new_stronghold,
                &stronghold_password,
                backup_path.clone(),
                &mut accounts,
                &mut new_secret_manager,
            )
            .await?;
        } else {
            // We'll create a new stronghold to load the backup
            let mut new_stronghold = StrongholdSecretManager::builder().try_build()?;
            read_data_from_stronghold_backup(
                self,
                &mut new_stronghold,
                &stronghold_password,
                backup_path,
                &mut accounts,
                &mut new_secret_manager,
            )
            .await?;
        }
````

Comment (thibault-martinez) [reply src/account_manager/operations/backup.rs]: No, just to set snapshot_path.

```rust
let snapshot_path = if let SecretManager::Stronghold(stronghold) = &mut *secret_manager {
    Somestronghold.snapshot_path.clone())
} else {
    None
};
```

Or something like this

File: src/account_manager/operations/backup.rs [hunk 2]
```diff
@@ -68,28 +68,25 @@ impl AccountManager {
...
-                &mut new_secret_manager,
-            )
-            .await?;
-        }
+            None
+        };
+
+        // We'll create a new stronghold to load the backup
+        let mut new_stronghold = StrongholdSecretManager::builder().try_build()?;
+        new_stronghold.snapshot_path = snapshot_path;
```
Comment (thibault-martinez) [inline src/account_manager/operations/backup.rs:80]: So what's happening if it's None ?

Comment (Thoralf-M) [reply src/account_manager/operations/backup.rs:80]: Then if you want to write the snapshot file you get `StrongholdSnapshotPathMissing`

Comment (Thoralf-M) [reply src/account_manager/operations/backup.rs:80]: Maybe we should make the snapshot path not optional in Stronghold, but that's not related to this PR

**Review by thibault-martinez — APPROVED** [review]

**Review by Tuditi — APPROVED** [review]
LGTM!
