### PR TITLE
Fix melting Native Token with foundry metadata

### LINKED ISSUE #1226: [Bug]: Native token melting fails if foundry has immutable metadata
### Issue description

Noticed through cli-wallet, but the bug is in wallet.rs:

The following method implements native token melting:
https://github.com/iotaledger/wallet.rs/blob/7bddeadaf6165285999c816116155083312cf5a9/src/account/operations/transaction/high_level/burning_melting/melt_native_token.rs#L40-L67

The problem in the method is on L53-L67, namely the creation of the next foundry output from the consumed one. The code does not account for immutable features in the consumed foundry (metadata for example), therefore the foundry transition and hence the transaction is invalid because it removes immutable features. (InvalidChainTransition, code 12).

Bonus question: What happens on L42?
https://github.com/iotaledger/wallet.rs/blob/7bddeadaf6165285999c816116155083312cf5a9/src/account/operations/transaction/high_level/burning_melting/melt_native_token.rs#L42
Why are we adding the balance of the consumed foundry to the alias? What's the point? The storage deposit requirement of the foundry will not change if you increase melted tokens count, so I'd suggest just use the balance of the consumed foundry for the output side foundry.

### Version

develop

### Expected behaviour

Melting doesn't fail if foundry has immutable features.

### Actual behaviour

It does.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. mint native tokens with metadata in the foundry
2. try to melt some

### Errors

_No response_

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by thibault-martinez**
Fixes #1226 

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/account/operations/transaction/high_level/burning_melting/melt_native_token.rs [hunk 1]
```diff
@@ -38,33 +34,23 @@ impl AccountHandle {
...
-                        )?),
-                    )?
-                    .add_unlock_condition(UnlockCondition::ImmutableAliasAddress(
-                        ImmutableAliasAddressUnlockCondition::new(AliasAddress::from(alias_id)),
-                    ))
-                    .finish()?,
-                ),
+                alias_output,
+                FoundryOutputBuilder::from(&existing_foundry_output)
+                    .with_minimum_storage_deposit(byte_cost_config)
```
Comment (Thoralf-M) [inline src/account/operations/transaction/high_level/burning_melting/melt_native_token.rs]: That should also not be required

**Review by Thoralf-M — APPROVED** [review]

**Review by samuel-rufi — APPROVED** [review]
