### PR TITLE
Mint more native token

### LINKED ISSUE #1333: High level function for minting of more native tokens
## Description

Add a high level function for minting of more native tokens when the foundry is owned by the account

## Motivation

Currently one can only mint native tokens during creation, but later not more

## Requirements

1. Add a new method which accepts the token id and the amount to be minted
2. Mint the additional native tokens if possible with the amount and if the foundry exists in the account

### LINKED ISSUE #1415: the semantic validation of a transaction failed with conflict reason: 9 - InvalidUnlock
## Bug description

the semantic validation of a transaction failed with conflict reason: 9 - InvalidUnlock
Happened during melting of native tokens

```
2022-09-07 08:10:07 (UTC) iota_wallet::account::operations::transaction DEBUG [TRANSACTION] conflict: InvalidUnlock for TransactionPayload { essence: Regular(RegularTransactionEssence { network_id: 8342982141227064571, inputs: BoxedSlicePrefix([Utxo(UtxoInput(0x443ea0fc001b9153aa1d5e516fcb124b93b1d3afcaf408119244dedb412951330100)), Utxo(UtxoInput(0x9c16cb248a194cdb5a3c1f80f48d41e45119dcbe5b38e6d914bdb714974fe8360000)), Utxo(UtxoInput(0x67ccfff02d357bc50d93bf6a29706c60433ccd79033bf8b474c1b1f53b24e58e0000))]), inputs_commitment: InputsCommitment(0x7f335b855aadadbf0f9b44e3fdc34f335027216e9412092864af22deb396fa65), outputs: BoxedSlicePrefix([Alias(AliasOutput { amount: BoundedU64(50300), native_tokens: NativeTokens(BoxedSlicePrefix([])), alias_id: AliasId(0xa337e1654340a82aea57470dcfe1899681923d67012a8d8224ea4b62ec8fcdd9), state_index: 3, state_metadata: BoxedSlicePrefix([]), foundry_counter: 2, unlock_conditions: UnlockConditions(BoxedSlicePrefix([StateControllerAddress(StateControllerAddressUnlockCondition(Ed25519(Ed25519Address(0x2967f17a9fd4c093376b114b548824d6da8eb5597ee55a19328ef369ffc293bc)))), GovernorAddress(GovernorAddressUnlockCondition(Ed25519(Ed25519Address(0x2967f17a9fd4c093376b114b548824d6da8eb5597ee55a19328ef369ffc293bc))))])), features: Features(BoxedSlicePrefix([])), immutable_features: Features(BoxedSlicePrefix([])) }), Foundry(FoundryOutput { amount: BoundedU64(52800), native_tokens: NativeTokens(BoxedSlicePrefix([])), serial_number: 1, token_scheme: Simple(SimpleTokenScheme { minted_tokens: 1000, melted_tokens: 100, maximum_supply: 1000 }), unlock_conditions: UnlockConditions(BoxedSlicePrefix([ImmutableAliasAddress(ImmutableAliasAddressUnlockCondition(Alias(AliasAddress(0xa337e1654340a82aea57470dcfe1899681923d67012a8d8224ea4b62ec8fcdd9))))])), features: Features(BoxedSlicePrefix([])), immutable_features: Features(BoxedSlicePrefix([])) }), Basic(BasicOutput { amount: BoundedU64(999844100), native_tokens: NativeTokens(BoxedSlicePrefix([NativeToken { token_id: TokenId(0x08a337e1654340a82aea57470dcfe1899681923d67012a8d8224ea4b62ec8fcdd90100000000), amount: 900 }, NativeToken { token_id: TokenId(0x08a337e1654340a82aea57470dcfe1899681923d67012a8d8224ea4b62ec8fcdd90200000000), amount: 1000 }])), unlock_conditions: UnlockConditions(BoxedSlicePrefix([Address(AddressUnlockCondition(Ed25519(Ed25519Address(0x2967f17a9fd4c093376b114b548824d6da8eb5597ee55a19328ef369ffc293bc))))])), features: Features(BoxedSlicePrefix([])) })]), payload: OptionalPayload(None) }), unlocks: Unlocks(BoxedSlicePrefix([Signature(SignatureUnlock(Ed25519(Ed25519Signature { public_key: 0x9914e4b7186b1e4a33ae5620fcdd3aa978a7309efa6e0a7bd932aab2ca6f56c2, signature: 0x22b47ddb7186c68424cc27eda5b1cc57b9bfbf8df4167056c20cde65cd6ae271e330b860ed386ba2749a33ef9a297b0c4ad322ac00c59327f5fc70a34e6a9402 }))), Reference(ReferenceUnlock(BoundedU16(0))), Reference(ReferenceUnlock(BoundedU16(0)))])) }
2022-09-07 08:10:07 (UTC) iota_wallet::account::operations::transaction DEBUG [TRANSACTION] Unlocked output 0x443ea0fc001b9153aa1d5e516fcb124b93b1d3afcaf408119244dedb412951330100 because of transaction error
2022-09-07 08:10:07 (UTC) iota_wallet::account::operations::transaction DEBUG [TRANSACTION] Unlocked output 0x9c16cb248a194cdb5a3c1f80f48d41e45119dcbe5b38e6d914bdb714974fe8360000 because of transaction error
2022-09-07 08:10:07 (UTC) iota_wallet::account::operations::transaction DEBUG [TRANSACTION] Unlocked output 0x67ccfff02d357bc50d93bf6a29706c60433ccd79033bf8b474c1b1f53b24e58e0000 because of transaction error
2022-09-07 08:10:07 (UTC) wallet::account                            ERROR wallet error: `the semantic validation of a transaction failed with conflict reason: 9 - InvalidUnlock`

```

### PR DESCRIPTION
**Pull request by Thoralf-M**
# Description of change

Mint more native token

## Links to any relevant issues

Fixes #1415 
Fixes https://github.com/iotaledger/wallet.rs/issues/1333

## Type of change

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Minting more native tokens with the cli wallet

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

File: bindings/nodejs/types/transactionOptions.ts [hunk 1]
```diff
@@ -34,6 +34,14 @@ export type CustomAddress = {
     value: string;
 };
 
+/** Native token options for minting more native tokens */
+export interface MintMoreNativeTokenOptions {
+    /** Hex encoded number */
+    additionalSupply: HexEncodedAmount;
+    /** Native token id */
+    tokenId: string;
+}
```
Comment (thibault-martinez) [inline bindings/nodejs/types/transactionOptions.ts]: Are we expecting more options? Otherwise these seem like very basic parameters that maybe should be part of the function signature?

File: src/account/operations/transaction/high_level/minting/mod.rs [hunk 2]
```diff
@@ -1,5 +1,6 @@
 // Copyright 2022 IOTA Stiftung
 // SPDX-License-Identifier: Apache-2.0
 
+pub(crate) mod mint_more_native_token;
```
Comment (thibault-martinez) [inline src/account/operations/transaction/high_level/minting/mod.rs]: Thinking out loud, don't mind me: I kinda feel like this should be better named `increaseNativeTokenSupply` but then melt should also be `decreaseNativeTokenSupply` which I agree would be different to the TIP (do we even care?). I just find it a tiny bit weird of a name atm.

Comment (Thoralf-M) [reply src/account/operations/transaction/high_level/minting/mod.rs]: Also not really happy with the naming

File: bindings/nodejs/types/transactionOptions.ts (hunk 1 above)
Comment (Thoralf-M) [reply bindings/nodejs/types/transactionOptions.ts]: Currently I don't expect more, one possible thing one could add would be `Option<String>` for an address to which the new minted tokens should go, but not sure if anyone cares about that, because then you also have to decide what should happen with the storage deposit if it's not your own address

Comment (thibault-martinez) [reply bindings/nodejs/types/transactionOptions.ts]: I'm fine keeping the options if we can already think of some, just saying that additionalSupply and tokenId are mandatory parameters and not really options 🤔

Comment (Thoralf-M) [reply bindings/nodejs/types/transactionOptions.ts]: Ah right, should I just change the name then?

Comment (thibault-martinez) [reply bindings/nodejs/types/transactionOptions.ts]: They are mandatory so they should be method parameters and not even in a struct IMO

Comment (Thoralf-M) [reply bindings/nodejs/types/transactionOptions.ts]: The supply fields in NativeTokenOptions are also mandatory, should they also be parameters? But having the different options split feels also weird

Comment (thibault-martinez) [reply bindings/nodejs/types/transactionOptions.ts]: Yeah but mandatory parameters are NOT options? To me, anything ending in `Options` should only contains `Option`s, mandatory things should be part of the API, I think it's clearer that way.

Comment (Thoralf-M) [reply bindings/nodejs/types/transactionOptions.ts]: You also have the option to set something to true or false, which could be mandatory, not optional, but still an option :trollface:

Comment (Thoralf-M) [reply bindings/nodejs/types/transactionOptions.ts]: But I'm fine with changing it to move not optional things to parameters

Comment (thibault-martinez) [reply bindings/nodejs/types/transactionOptions.ts]: If we do that, do you think we should keep the options even if empty at the moment just to avoid any future breaking change?

Comment (Thoralf-M) [reply bindings/nodejs/types/transactionOptions.ts]: Would still be a breaking change, no?

Comment (thibault-martinez) [reply bindings/nodejs/types/transactionOptions.ts]: If the members are private and we provide new and getters it should be fine ? Overall I think we have way too many structs with public fields, I think we should change that before the release.

Comment (Thoralf-M) [reply bindings/nodejs/types/transactionOptions.ts]: Ah yeah if they're private it should work

Comment (Thoralf-M) [reply bindings/nodejs/types/transactionOptions.ts]: @thibault-martinez is it now like you imagined it? (Only Rust part, didn't update bindings yet)

File: bindings/nodejs/lib/Account.ts [hunk 3]
```diff
@@ -536,6 +537,31 @@ export class Account {
...
 
+    /**
+     * Mint more native tokens.
+     * @param mintMoreNativeTokenOptions The options for minting more tokens.
+     * @param transactionOptions The options to define a `RemainderValueStrategy`
+     * or custom inputs.
+     * @returns The minting transaction and the token ID.
+     */
+    async mintMoreNativeToken(
+        mintMoreNativeTokenOptions: MintMoreNativeTokenOptions,
```
Comment (thibault-martinez) [inline bindings/nodejs/lib/Account.ts]: Forgot to update the bindings

Comment (Thoralf-M) [reply bindings/nodejs/lib/Account.ts]: No, https://github.com/iotaledger/wallet.rs/pull/1418#discussion_r966973844 :trollface:

Comment (thibault-martinez) [reply bindings/nodejs/lib/Account.ts]: Oh sorry, don't think I received a notification for this one

File: bindings/nodejs/types/transactionOptions.ts (hunk 1 above)
Comment (thibault-martinez) [reply bindings/nodejs/types/transactionOptions.ts]: Yeah, LGTM

**Review by thibault-martinez — COMMENTED** [review]
Maybe add a .change so that it's clear to the FF team what changed

File: bindings/nodejs/lib/Account.ts [hunk 4]
```diff
@@ -496,21 +500,24 @@ export class Account {
...
-     * @param nativeToken The Native Token with amount.
+     * @param tokenId The native token id.
+     * @param meltAmount To be melted amount.
      * @param transactionOptions The options to define a `RemainderValueStrategy`
      * or custom inputs.
      * @returns The transaction.
      */
-    async meltNativeToken(
-        nativeToken: [string, HexEncodedAmount],
+    async decreaseNativeTokenSupply(
```
Comment (thibault-martinez) [inline bindings/nodejs/lib/Account.ts:509]: Do you think there could be options at some point ?

File: examples/11_melt_native_token.rs [hunk 5]
```diff
@@ -1,7 +1,7 @@
 // Copyright 2022 IOTA Stiftung
 // SPDX-License-Identifier: Apache-2.0
 
-//! cargo run --example 11_melt_native_token --release
+//! cargo run --example 11_decrease_native_token_supply --release
```
Comment (thibault-martinez) [inline examples/11_melt_native_token.rs]: Change the file name as well ?

File: bindings/nodejs/lib/Account.ts (hunk 4 above)
Comment (Thoralf-M) [reply bindings/nodejs/lib/Account.ts:509]: Can't think of anything that isn't in the transaction options already

File: examples/11_melt_native_token.rs (hunk 5 above)
Comment (Thoralf-M) [reply examples/11_melt_native_token.rs]: Ahh, I actually changed it back because melting is shorter and still makes sense :trollface:
So I could update the comment or change the file name, what do you think is less confusing?

Comment (thibault-martinez) [reply examples/11_melt_native_token.rs]: Since it's user facing I would harmonise everything so that they are not confused if the file is called melting but we never call anything called "melt*"

File: examples/11_decrease_native_token_supply.rs [hunk 6]
```diff
@@ -1,7 +1,7 @@
 // Copyright 2022 IOTA Stiftung
 // SPDX-License-Identifier: Apache-2.0
 
-//! cargo run --example 11_melt_native_token --release
+//! cargo run --example decrease_native_token_supply --release
```
Comment (thibault-martinez) [inline examples/11_decrease_native_token_supply.rs:4]: Can you add a small similar example for increase pls ?

File: src/account/types/mod.rs [hunk 7]
```diff
@@ -112,15 +112,18 @@ impl OutputData {
     ) -> crate::Result<InputSigningData> {
         let unlock_address = {
             if let Some(unlock_conditions) = self.output.unlock_conditions() {
-                *unlock_conditions.locked_address(&self.address, current_time)
+                match &self.output {
+                    Output::Foundry(foundry) => Address::Alias(*foundry.alias_address()),
```
Comment (thibault-martinez) [inline src/account/types/mod.rs:116]: What is in `self.address` in case of a foundry?

Comment (Thoralf-M) [reply src/account/types/mod.rs:116]: The ed25519 address for which we got the alias output, which then owns the foundry output

**Review by thibault-martinez — APPROVED** [review]

**Review by samuel-rufi — APPROVED** [review]
