### PR TITLE
Java: jni rewrite with error handling

### LINKED ISSUE #1603: Review JNI exception handling + unwraps()

### PR DESCRIPTION
**Pull request by kwek20**
# Description of change

Updated jni rust code with more complete exception handling

(Did i go overkill with macros?)

## Links to any relevant issues

fixes issue #1603 

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

### CODE REVIEW

File: bindings/java/iota-wallet-java/lib/native/src/lib.rs [hunk 1]
```diff
@@ -27,10 +27,52 @@ lazy_static! {
     static ref METHOD_CACHE: Mutex<Option<JStaticMethodID>> = Mutex::new(None);
 }
 
+// A macro that checks if the result is an error and throws an exception if it is.
+macro_rules! jni_err_assert {
```
Comment (samuel-rufi) [inline bindings/java/iota-wallet-java/lib/native/src/lib.rs]: As you mentioned in the PR, using macros here might be a bit overkill. I'm for as easy code as possible here (also since this Rust<->JVM logic isn't so trivial), can you avoid macros if possible?

File: bindings/java/iota-wallet-java/lib/native/src/lib.rs [hunk 2]
```diff
@@ -27,10 +27,52 @@ lazy_static! {
...
+// it throws an exception and returns the value of r.
+macro_rules! string_from_jni {
+    ($env:ident, $x:ident, $r:expr ) => {{
+        let string = $env.get_string($x);
+        String::from(jni_err_assert!($env, string, $r))
+    }};
+}
+
+// Getting a string from the JNIEnv and then checking if it is an error. If it is an error,
+// it throws an exception and returns the value of r.
```
Comment (samuel-rufi) [inline bindings/java/iota-wallet-java/lib/native/src/lib.rs]: Same comment as in line 41/42, one should be different

File: bindings/java/iota-wallet-java/lib/native/src/lib.rs [hunk 3]
```diff
@@ -27,10 +27,52 @@ lazy_static! {
...
+        }
+    }};
+}
+
 // This keeps rust from "mangling" the name and making it unique for this crate.
 #[no_mangle]
 pub extern "system" fn Java_org_iota_api_NativeApi_initLogger(env: JNIEnv, _class: JClass, command: JString) {
-    let config_builder: String = env.get_string(command).expect("Couldn't get java string!").into();
+    // This is a safety check to make sure that the JNIEnv is not in an exception state.
+    env_assert!(env,());
```
Comment (samuel-rufi) [inline bindings/java/iota-wallet-java/lib/native/src/lib.rs]: When this throws an exception it will however continue to process the Rust code below which doesn't sound good. Can you return here after the exception was thrown? Also needs to be done for the other functions.

File: bindings/java/iota-wallet-java/lib/native/src/lib.rs [hunk 4]
```diff
@@ -104,39 +135,30 @@ pub extern "system" fn Java_org_iota_api_NativeApi_sendMessage(
...
-    if env.exception_check().unwrap() {
-        return std::ptr::null_mut();
-    }
+    env_assert!(env, std::ptr::null_mut());
 
-    match MESSAGE_HANDLER.lock() {
-        Ok(message_handler_store) => match message_handler_store.as_ref() {
-            Some(message_handler) => {
-                let command: String = env.get_string(command).expect("Couldn't get java string!").into();
+    let message = jni_from_json_make!(env, command, Message, std::ptr::null_mut());
```
Comment (samuel-rufi) [inline bindings/java/iota-wallet-java/lib/native/src/lib.rs]: Sometimes we pass `()` and sometimes we pass `std::ptr::null_mut()`, I unfortunately don't understand fully what's going on? Do we even need to pass that stuff?

File: bindings/java/iota-wallet-java/lib/native/src/lib.rs [hunk 5]
```diff
@@ -27,10 +27,52 @@ lazy_static! {
...
 }
 
+// A macro that checks if the result is an error and throws an exception if it is.
+macro_rules! jni_err_assert {
+    ($env:ident, $result:expr, $ret:expr ) => {{
+        if let Err(err) = $result {
+            throw_exception(&$env, err.to_string());
+            return $ret;
+        }
+        $result.unwrap()
```
Comment (samuel-rufi) [inline bindings/java/iota-wallet-java/lib/native/src/lib.rs]: could you please add a comment to all `.unwrap()` on why its safe to unwrap

**Review by samuel-rufi — CHANGES_REQUESTED** [review]

File: bindings/java/lib/native/src/lib.rs [hunk 6]
```diff
@@ -150,77 +178,108 @@ pub unsafe extern "system" fn Java_org_iota_api_NativeApi_listen(
...
             }
+            _ => throw_nullpointer(&env, "Wallet not initialised."),
         },
-        Err(err) => {
-            env.throw_new("java/lang/Exception", err.to_string()).unwrap();
-            std::ptr::null_mut()
+        Err(err) => throw_exception(&env, err.to_string()),
+    };
+
+    // exceptions return early, let the client now we registered successfully
```
Comment (Thoralf-M) [inline bindings/java/lib/native/src/lib.rs]: Don't understand this part `let the client now we registered`

Comment (kwek20) [reply bindings/java/lib/native/src/lib.rs]: now -> know. typo :D

**Review by Thoralf-M — APPROVED** [review]

**Review by samuel-rufi — APPROVED** [review]
